In [1]:
import numpy as np
li_arr=[i for i in range(0,100)]
np_arr=np.array(100)
print(li_arr)
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
100


numpy is faster because of vectorisation

In [3]:
a=[1,2,3,'5',4.6]
b=np.array(a)
print(b)

['1' '2' '3' '5' '4.6']


In [6]:
from numpy import dtype


a=[1,2,3,'5',4.6]
b=np.array(a,dtype=int)
print(b)

[1 2 3 5 4]


numpy uses only homogeneous type

In [7]:
a=[1,2,3,'5','a',4.6]
b=np.array(a)
print(b)

['1' '2' '3' '5' 'a' '4.6']


In [8]:
a=[1,2,3,'5','6',4.6]
b=np.array(a,dtype=str)
print(b)

['1' '2' '3' '5' '6' '4.6']


In [14]:
c=np.ones(3,dtype=int)
d=np.array(a*3)
e=np.zeros(5,dtype=int)
print(c)
print(d)
print(e)

[1 1 1]
['1' '2' '3' '5' '6' '4.6' '1' '2' '3' '5' '6' '4.6' '1' '2' '3' '5' '6'
 '4.6']
[0 0 0 0 0]


In [15]:
f=np.zeros((3,3),dtype=int)
print(f)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [18]:
b=np.zeros((3,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
b=np.full(3,5)
print(b)

[5 5 5]


In [21]:
b=np.full((3,3),5,dtype=int)
print(b)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [24]:
a = np.empty(4, dtype = int)
print(a)

[0 0 0 0]


In [26]:
d=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
e=np.array(d)
print(type(e))

<class 'numpy.ndarray'>


In [33]:
f=np.zeros(10,dtype=int)

f[4]=1
print(f)
print(type(f))

[0 0 0 0 1 0 0 0 0 0]
<class 'numpy.ndarray'>


np.arage

In [36]:
a=np.arange(10)
a=np.arange(2,20,2)
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


np.linespace

In [43]:
b=np.linspace(2,10,10,dtype=int) #50 samples by default
print(b)
print(b[2]-b[1])
print(b[4]-b[3])

[ 2  2  3  4  5  6  7  8  9 10]
1
1


In [45]:
b=np.linspace(2,10,10,dtype=int,endpoint=False)
print(b)

[2 2 3 4 5 6 6 7 8 9]


In [47]:
print(np.identity(3))
print(np.eye(3,4))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [49]:
a=np.random.rand(3)
print(a)

[0.36369111 0.74025949 0.27235072]


In [58]:
a=np.random.rand(3)
print(a)
a.shape

[0.99438984 0.59228207 0.58561766]


(3,)

In [62]:
np.random.rand()

0.7945616646741107

In [53]:
print(np.random.rand(10)*10) #values getting multiplies by 10

[3.34325438 1.64810652 9.78556972 5.44680014 9.26937637 9.29081901
 9.23876797 3.01766996 9.40857304 4.65111391]


In [55]:
a = np.array([0, 1, 2, 3])
print(a)
a.shape

[0 1 2 3]


(4,)

numpy create array with values from 9 to 49 consecutively

In [63]:
a=np.arange(9,50)
print(a)

[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


Create an integer identity matrix of size (5, 6).
Print the Numpy array.

In [65]:
b=np.eye(5,6,dtype=int)
print(b)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
Note:Array elements are the points where cut is to be made and round upto 2 decimal place.
Print the array element.

In [70]:
c=np.arange(0,5,0.5)
print(c)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [71]:
c=np.linspace(0,5,10)
print(c)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


indexing and slicing

In [73]:
li=[1,2,3,4,4,5,5,6,6]
arr=np.array(li)
li_2d=[[1,2,3,4],[5,6,7,8],[9,8,7,6],[5,4,3,2]]
arr_2d=np.array(li_2d)

In [ ]:
print(li_2d[2][1])
print(arr_2d[2][1])
print(arr_2d[2,1])

In [ ]:
print(li_2d[1][:3])
print(arr_2d[1,:3])


In [74]:
print(li_2d[:3][2]) # gives something else
print(arr_2d[:3,2])

[9, 8, 7, 6]
[3 7 7]


In [75]:
print(li_2d[2:4][1:3])
print(arr_2d[2:4,1:3])

[[5, 4, 3, 2]]
[[8 7]
 [4 3]]


Mathematical operations

In [78]:
li=[1,2,3,4,5,6]
a=np.random.randint(1,20,5) #why 5 array size
b=np.random.randint(1,20,5)

In [76]:
li=[i+1 for i in li]
li

[2, 3, 4, 5, 5, 6, 6, 7, 7]

In [79]:
a=a+1
a

array([12, 20,  2,  7, 10])

In [ ]:
c=a+b
d=a-b
e=a/b
f=a//b

In [81]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.max())
print(a.argmin()) #index of min
print(a.argmin()) #index of max

[12 20  2  7 10]
51
10.2
2
20
2
2


In [83]:
print(a<b)
print(a>b)
print(a==b)
print(np.logical_not(a))

[False False  True False False]
[ True  True False  True  True]
[False False False False False]
[False False False False False]


boolean indexing

In [84]:
a=np.array(['f','4','t','g'])
b=np.random.randint(1,20,8)
print(b)
print(b>10)

[ 7  8  1 12 18  5 16 11]
[False False False  True  True False  True  True]


In [85]:
bool_arr=b>10
new_arr=b[bool_arr]
print(new_arr)

[12 18 16 11]


In [86]:
c=b
c

array([ 7,  8,  1, 12, 18,  5, 16, 11])

In [87]:
c[:3]=19
c

array([19, 19, 19, 12, 18,  5, 16, 11])

In [91]:
c[c>15]
c[c>15]=1
c

array([ 1,  1,  1, 12,  1,  5,  1, 11])

In [92]:
print(b)

[ 1  1  1 12  1  5  1 11]


In [97]:
x=np.where(b==1)
x

(array([0, 1, 2, 4, 6]),)

In [99]:
c=np.array([1,2,3,4,5,7,8,9])
print(c[x])

[1 2 3 5 8]


Find indices of non-zero elements from the array
[1,2,0,0,4,0] ?
Print the index of non-zero elements.

In [100]:
a=np.array([1,2,0,0,4,0])
c=np.where(a!=0)
c

(array([0, 1, 4]),)

Given an integer array of size 10. Print the index of elements which are multiple of 3.
Note: Generate the following array
array(I 1, 3, 5, 7, 9, 11, 13, 15, 17, 19])

In [101]:
a=np.array([ 1, 3, 5, 7, 9, 11, 13, 15, 17, 19])
b=np.where(a%3==0)
b

(array([1, 4, 7]),)

Given an integer array of size 10. Replace the odd number in numpy array with -1 ?
Note: Generate the following array
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [103]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b=np.where(a%2==0)
a[b]=-1
a

array([ 1, -1,  3, -1,  5, -1,  7, -1,  9, -1])

Given an integer array of size 10 and replace the first occurrence of maximum value by 0?
Note: Generate the following array
array ([11, 2, 13, 4, 15, 6, 27, 8, 19])

In [104]:
a=np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
b=np.argmax(a)
a[b]=0
a

array([11,  2, 13,  4, 15,  6,  0,  8, 19])

Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?
Note: Generate the following array
array ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [109]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b=np.where((a>3)&(a<9))
a[b]=-a[b]
a

array([ 1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm.
Print the Numpy array.

In [112]:
heights=np.array([121,156,181,134,178,111,144])
age=np.array([23,24,25,26,27,28,29])
x=np.where(heights>155)
print(age[x])

[24 25 27]


2d boolean indexing

In [121]:
a=np.random.randint(1,30,(5,6))
a

array([[25, 24, 16,  9, 28, 19],
       [ 2,  4, 26, 21, 25, 12],
       [14,  5, 15,  3, 17, 19],
       [ 3,  4, 28,  6,  4, 13],
       [23,  2, 26, 13,  1, 16]])

In [122]:
bool_arr=a>20
bool_arr
a[bool_arr]

array([25, 24, 28, 26, 21, 25, 28, 23, 26])

In [118]:
b=a
b[bool_arr]=100
b

array([[ 17,   2,  16,  19,  13,   6],
       [100, 100, 100,   5,  10, 100],
       [ 20, 100,  10, 100,   1,  12],
       [100,  15, 100, 100,  16,  18],
       [ 18,   1,  11, 100,  11,   1]])

make sure boolean array is of same shape as original array

In [123]:
bool_arr=b[:,3]==100
bool_arr

array([False, False,  True,  True,  True])

In [124]:
b[bool_arr,3]=99
b

array([[ 17,   2,  16,  19,  13,   6],
       [100, 100, 100,   5,  10, 100],
       [ 20, 100,  10,  99,   1,  12],
       [100,  15, 100,  99,  16,  18],
       [ 18,   1,  11,  99,  11,   1]])

Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
That means, we should re-arrange complete row based on 2nd columns' values.
Given 2D array is:
[[21 20 19 18 17]
[16 15 14 13 12]
[11 10 9 8 7]
[6 5 4 3 21]]

Print the 2D array in sorted order.
Note you have to generate the 2D Array.Here 2nd column means column present at index 1.
Output Format :
[[6 5 4 3 21]
[11 10 9 8 7]
[16 15 14 13 12]
[21 20 19 18 17]]

In [125]:
a=np.array([[21,20,19,18,17],[16,15,14,13,12],[11,10,9,8,7],
[6,5,4,3,21]]
)
a

array([[21, 20, 19, 18, 17],
       [16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7],
       [ 6,  5,  4,  3, 21]])

In [128]:
np.sort(a[:,1])

array([ 5, 10, 15, 20])

In [131]:
a[:,1].argsort()

array([3, 2, 1, 0])

In [130]:
a[a[:,1].argsort()]

array([[ 6,  5,  4,  3, 21],
       [11, 10,  9,  8,  7],
       [16, 15, 14, 13, 12],
       [21, 20, 19, 18, 17]])

working with different size arrays- Broadcasting

In [132]:
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,3)
print(x)
print(y)

[[8 8 5]
 [8 9 1]
 [9 9 5]]
[8 5 2]


In [133]:
print(x-y)

[[ 0  3  3]
 [ 0  4 -1]
 [ 1  4  3]]


working with csv file

In [144]:
import csv
file_obj=open("datasets/year2017.csv")
data=csv.DictReader(file_obj,skipinitialspace=True)

In [145]:
killed=[]
wounded=[]
country=[]
for row in data:
    killed.append(row['Killed'])
    wounded.append(row['Wounded'])
    country.append(row['Country'])
    
np_killed=np.array(killed)
np_wounded=np.array(wounded)

np_killed[np_killed==""]='0.0'
np_wounded[np_wounded==""]='0.0'

np_killed=np.array(np_killed,dtype=float)
np_wounded=np.array(np_wounded,dtype=float)

kill_wounded=np_killed+np_wounded
kill_wounded



array([0., 2., 7., ..., 0., 0., 0.])

In [146]:
np_country=np.array(country)
bool_arr=np_country=="India"
ans=kill_wounded[bool_arr]


array([ 0.,  1.,  4.,  1.,  1.,  0.,  2.,  2.,  0.,  1.,  2.,  2.,  1.,
        0.,  1.,  4.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  4.,  1.,  2.,
        1.,  0.,  5.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  7.,  0.,  1.,
        0.,  0.,  0.,  0.,  0.,  4.,  0., 95.,  0.,  2.,  0.,  1.,  0.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  2.,  0.,  1.,  1., 18.,  2., 13.,  1.,
        0.,  3.,  0.,  1.,  0.,  0.,  0.,  1.,  1., 10.,  0.,  0.,  1.,
        1.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  2.,  1.,  0.,  4.,
        0.,  0.,  0.,  0.,  0.,  1.,  0.,  5.,  2.,  0.,  0.,  0.,  2.,
        1.,  2.,  0.,  0.,  0.,  0.,  1.,  1.,  4.,  1.,  0.,  0.,  1.,
        1.,  1.,  9.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
        0.,  8.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  1.,
        0.,  3.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  1.,  1.,  0

In [147]:
np.sum(ans)

1167.0